R4:
  hostname: 172.16.32.188
  groups:
    - iosxe
  data:
    interfaces:
        - name: ethernet 0/2
          vrfv:  1
          ip:   192.168.1.10
          mask: 255.255.255.0
          desc: VRF1
        - name: ethernet 0/1
          vrfv:  2
          ip:   192.168.1.10
          mask: 255.255.255.0
          desc: VRF2
    vrfs:
        - def: 1
          rd: 1:1
          rt: 1:1
        - def: 2
          rd: 2:2
          rt: 2:2
    bgps:
        - bgpnu: 100
          neighbor: 5.5.5.5
    rips:
        - net1: 6.6.6.6
          net2: 192.168.1.0
          net3: 192.168.0.0
          vrfv: 1


R5:
  hostname: 172.16.32.187
  groups:
    - iosxe
  data:
    interfaces:
        - name: ethernet 0/2
          vrfv:  1
          ip:   192.168.2.10
          mask: 255.255.255.0
          desc: VRF1
        - name: ethernet 0/1
          vrfv:  2
          ip:   192.168.2.10
          mask: 255.255.255.0
          desc: VRF2
    vrfs:
        - def: 1
          rd: 1:1
          rt: 1:1
        - def: 2
          rd: 2:2
          rt: 2:2
    bgps:
        - bgpnu: 100
          neighbor: 4.4.4.4
    rips:
        - net1: 9.9.9.9
          net2: 192.168.2.0
          net3: 192.168.0.0
          vrfv: 1
